CREATE TABLE guests (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  pwd_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE bookings ADD COLUMN guest_id INTEGER REFERENCES guests(id);
